# Generated by Django 5.1.5 on 2025-01-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='end_production',
            field=models.DateField(blank=True, null=True),
        ),
    ]
